name: Deploy Catalog API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build project
        run: mvn clean package -DskipTests=true

      - name: Run tests
        run: mvn clean test verify

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/catalog-api:${{ github.run_id }} .

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Push Docker Image
        run: |
          docker tag ${{secrets.DOCKER_USERNAME}}/catalog-api:${{ github.run_id }} ${{secrets.DOCKER_USERNAME}}/catalog-api:latest

          docker push ${{secrets.DOCKER_USERNAME}}/catalog-api:${{ github.run_id }}
          docker push ${{secrets.DOCKER_USERNAME}}/catalog-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from Docker Hub
        run: docker pull guilhermeozana/catalog-api:latest

      - name: Remove existent docker container
        run: docker container rm -f catalog-api

      - name: Run Docker container
        run: |
          docker run --name catalog-api \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
          -e MONGODB_URI=${{ secrets.MONGO_URI }} \
          --network=anotaai-network guilhermeozana/catalog-api:latest
          
          
          
